# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.persistent_streams_api import PersistentStreamsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPersistentStreamsApi(unittest.TestCase):
    """PersistentStreamsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.persistent_streams_api.PersistentStreamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_pstream(self):
        """Test case for add_pstream

        Add a pstream  # noqa: E501
        """
        pass

    def test_delete_pstream(self):
        """Test case for delete_pstream

        Delete a pstream.  # noqa: E501
        """
        pass

    def test_edit_pstream(self):
        """Test case for edit_pstream

        Edit attributes of a pstream  # noqa: E501
        """
        pass

    def test_get_pstream_data(self):
        """Test case for get_pstream_data

        Get data of a pstream  # noqa: E501
        """
        pass

    def test_get_pstreams(self):
        """Test case for get_pstreams

        Fetch meta data about pstreams  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
