# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.pstreams_enum import PstreamsEnum  # noqa: E501
from openapi_client.rest import ApiException

class TestPstreamsEnum(unittest.TestCase):
    """PstreamsEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPstreamsEnum(self):
        """Test PstreamsEnum"""
        # inst = PstreamsEnum()

if __name__ == '__main__':
    unittest.main()
