# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.pstream_add_model import PstreamAddModel  # noqa: E501
from openapi_client.rest import ApiException

class TestPstreamAddModel(unittest.TestCase):
    """PstreamAddModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PstreamAddModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PstreamAddModel`
        """
        model = openapi_client.models.pstream_add_model.PstreamAddModel()  # noqa: E501
        if include_optional :
            return PstreamAddModel(
                name = '', 
                attributes = openapi_client.models.attributes.Attributes()
            )
        else :
            return PstreamAddModel(
                name = '',
        )
        """

    def testPstreamAddModel(self):
        """Test PstreamAddModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
