# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.table_report_response import TableReportResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestTableReportResponse(unittest.TestCase):
    """TableReportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TableReportResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableReportResponse`
        """
        model = openapi_client.models.table_report_response.TableReportResponse()  # noqa: E501
        if include_optional :
            return TableReportResponse(
                last_sort_results = [
                    ''
                    ], 
                report_meta_data = openapi_client.models.reportmetadata.Reportmetadata(), 
                offset = 56, 
                limit = 56, 
                sort = [
                    ''
                    ], 
                total_count = 56, 
                num_items = 56, 
                is_first = True, 
                is_last = True
            )
        else :
            return TableReportResponse(
        )
        """

    def testTableReportResponse(self):
        """Test TableReportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
