# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.dashboards_api import DashboardsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.dashboards_api.DashboardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_browseapi_api_v2_dashboards_get(self):
        """Test case for browseapi_api_v2_dashboards_get

        Fetch dashboards definitions accessible for current user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
