# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PstreamsEnum(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    COLLECTION_STATUS = 'collection_status'
    MINUS_COLLECTION_STATUS = '-collection_status'
    DATABASE = 'database'
    MINUS_DATABASE = '-database'
    DATASTORE_TYPE = 'datastore_type'
    MINUS_DATASTORE_TYPE = '-datastore_type'
    INDEX_NAME = 'index_name'
    MINUS_INDEX_NAME = '-index_name'
    NAME = 'name'
    MINUS_NAME = '-name'
    RETENTION_DAYS = 'retention_days'
    MINUS_RETENTION_DAYS = '-retention_days'
    SAVED_TIME = 'saved_time'
    MINUS_SAVED_TIME = '-saved_time'
    SYSTEM_DEFINED = 'system_defined'
    MINUS_SYSTEM_DEFINED = '-system_defined'
    TIMESTAMP = 'timestamp'
    MINUS_TIMESTAMP = '-timestamp'

    @classmethod
    def from_json(cls, json_str: str) -> PstreamsEnum:
        """Create an instance of PstreamsEnum from a JSON string"""
        return PstreamsEnum(json.loads(json_str))


