# coding: utf-8

"""
    CloudFabrix RDA Platform API

    CloudFabrix RDA Platform API  # noqa: E501

    The version of the OpenAPI document: 3.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from pydantic import Field, StrictStr, conint, conlist

from typing import Optional

from cfx_rda_api.models.dashboards_enum import DashboardsEnum
from cfx_rda_api.models.table_report_response import TableReportResponse

from cfx_rda_api.api_client import ApiClient
from cfx_rda_api.api_response import ApiResponse
from cfx_rda_api.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class DashboardsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_dashboards(self, cfxql_query : Annotated[Optional[StrictStr], Field(description="<a href='https://bot-docs.cloudfabrix.io/reference_guides/cfxql/'>cfxql query</a> string to filter the results")] = None, search : Annotated[Optional[StrictStr], Field(description="search across fields: ['name', 'description', 'usecase', 'category', 'version']")] = None, offset : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Offset to start the results from.")] = None, limit : Annotated[Optional[conint(strict=True, ge=1)], Field(description="Maximum number of results to return")] = None, sort : Annotated[Optional[conlist(DashboardsEnum)], Field(description="Sort the output based on given fields")] = None, **kwargs) -> TableReportResponse:  # noqa: E501
        """Fetch meta data for dashboards  # noqa: E501

        Fetch meta data for dashboards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_dashboards(cfxql_query, search, offset, limit, sort, async_req=True)
        >>> result = thread.get()

        :param cfxql_query: <a href='https://bot-docs.cloudfabrix.io/reference_guides/cfxql/'>cfxql query</a> string to filter the results
        :type cfxql_query: str
        :param search: search across fields: ['name', 'description', 'usecase', 'category', 'version']
        :type search: str
        :param offset: Offset to start the results from.
        :type offset: int
        :param limit: Maximum number of results to return
        :type limit: int
        :param sort: Sort the output based on given fields
        :type sort: List[DashboardsEnum]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TableReportResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_dashboards_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_dashboards_with_http_info(cfxql_query, search, offset, limit, sort, **kwargs)  # noqa: E501

    @validate_arguments
    def get_dashboards_with_http_info(self, cfxql_query : Annotated[Optional[StrictStr], Field(description="<a href='https://bot-docs.cloudfabrix.io/reference_guides/cfxql/'>cfxql query</a> string to filter the results")] = None, search : Annotated[Optional[StrictStr], Field(description="search across fields: ['name', 'description', 'usecase', 'category', 'version']")] = None, offset : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Offset to start the results from.")] = None, limit : Annotated[Optional[conint(strict=True, ge=1)], Field(description="Maximum number of results to return")] = None, sort : Annotated[Optional[conlist(DashboardsEnum)], Field(description="Sort the output based on given fields")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Fetch meta data for dashboards  # noqa: E501

        Fetch meta data for dashboards  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_dashboards_with_http_info(cfxql_query, search, offset, limit, sort, async_req=True)
        >>> result = thread.get()

        :param cfxql_query: <a href='https://bot-docs.cloudfabrix.io/reference_guides/cfxql/'>cfxql query</a> string to filter the results
        :type cfxql_query: str
        :param search: search across fields: ['name', 'description', 'usecase', 'category', 'version']
        :type search: str
        :param offset: Offset to start the results from.
        :type offset: int
        :param limit: Maximum number of results to return
        :type limit: int
        :param sort: Sort the output based on given fields
        :type sort: List[DashboardsEnum]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TableReportResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'cfxql_query',
            'search',
            'offset',
            'limit',
            'sort'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_dashboards" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('cfxql_query') is not None:  # noqa: E501
            _query_params.append(('cfxql_query', _params['cfxql_query']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('offset') is not None:  # noqa: E501
            _query_params.append(('offset', _params['offset']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('sort') is not None:  # noqa: E501
            _query_params.append(('sort', _params['sort']))
            _collection_formats['sort'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TableReportResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v2/dashboards', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
